/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Active portfolio position with invested/market values and P/L
 */
export interface ActivePositionResponse { 
    platform?: ActivePositionResponse.PlatformEnum;
    type?: ActivePositionResponse.TypeEnum;
    ticker?: string;
    name?: string;
    shares?: number;
    avgPriceEur?: number;
    investedEur?: number;
    investedPercentage?: number;
    profitLossEur?: number;
    profitLossPercentage?: number;
    marketValueEur?: number;
    marketValuePercentage?: number;
}
export namespace ActivePositionResponse {
    export const PlatformEnum = {
        Trading212: 'TRADING212',
        Etoro: 'ETORO',
        Ibkr: 'IBKR',
        Revolut: 'REVOLUT'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
    export const TypeEnum = {
        Stock: 'STOCK',
        Etf: 'ETF'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


