/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetSimpleResponse { 
    id?: string;
    symbol?: string;
    name?: string;
    type?: AssetSimpleResponse.TypeEnum;
}
export namespace AssetSimpleResponse {
    export const TypeEnum = {
        Stock: 'STOCK',
        Etf: 'ETF'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


