/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Individual stock/etf holding details
 */
export interface AssetHoldingResponse { 
    platform?: AssetHoldingResponse.PlatformEnum;
    type?: AssetHoldingResponse.TypeEnum;
    ticker?: string;
    name?: string;
    shares?: number;
    avgPrice?: number;
    currentPrice?: number;
    profitLoss?: number;
    profitLossPercentage?: number;
    portfolioPercentage?: number;
}
export namespace AssetHoldingResponse {
    export const PlatformEnum = {
        Trading212: 'TRADING212',
        Etoro: 'ETORO',
        Ibkr: 'IBKR',
        Revolut: 'REVOLUT'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
    export const TypeEnum = {
        Stock: 'STOCK',
        Etf: 'ETF'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


