/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetAliasResponse } from './asset-alias-response';
import { CompanyResponse } from './company-response';
import { ExchangeResponse } from './exchange-response';


export interface AssetResponse { 
    id?: string;
    type?: AssetResponse.TypeEnum;
    symbol?: string;
    company?: CompanyResponse;
    currency?: string;
    exchange?: ExchangeResponse;
    aliases?: Array<AssetAliasResponse>;
}
export namespace AssetResponse {
    export const TypeEnum = {
        Stock: 'STOCK',
        Etf: 'ETF'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


