/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetDividendCostYieldResponse { 
    assetId?: string;
    ticker?: string;
    name?: string;
    totalDividendEur?: number;
    annualizedDividendEur?: number;
    costBasisEur?: number;
    daysHeld?: number;
    dividendCostYield?: number;
}

