/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Individual company/etf holding details
 */
export interface CompanyAssetHoldingResponse { 
    platform?: CompanyAssetHoldingResponse.PlatformEnum;
    tickers?: Array<string>;
    name?: string;
    profitLoss?: number;
    profitLossPercentage?: number;
    portfolioPercentage?: number;
    dividendCostYield?: number;
}
export namespace CompanyAssetHoldingResponse {
    export const PlatformEnum = {
        Trading212: 'TRADING212',
        Etoro: 'ETORO',
        Ibkr: 'IBKR',
        Revolut: 'REVOLUT'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


