/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetDividendCostYieldResponse } from './asset-dividend-cost-yield-response';
import { TotalDividendCostYieldResponse } from './total-dividend-cost-yield-response';


export interface DividendCostYieldResponse { 
    assets?: Array<AssetDividendCostYieldResponse>;
    total?: TotalDividendCostYieldResponse;
}

