/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SectorSimpleResponse } from './sector-simple-response';


export interface IndustryResponse { 
    id?: string;
    name?: string;
    sector?: SectorSimpleResponse;
}

