/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetSimpleResponse } from './asset-simple-response';


export interface PerformerResponse { 
    asset?: AssetSimpleResponse;
    percentageChange?: number;
}

