/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Change information for a specific period
 */
export interface PeriodChangeResponse { 
    startDate?: string;
    endDate?: string;
    periodDays?: number;
    changeAmount?: number;
    changePercentage?: number;
    periodLabel?: string;
}

