/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IndustrySectorValueResponse } from './industry-sector-value-response';
import { CountryValueResponse } from './country-value-response';
import { AssetTypeValueResponse } from './asset-type-value-response';
import { CurrencyValueResponse } from './currency-value-response';


export interface PortfolioAllocationResponse { 
    byCurrency?: Array<CurrencyValueResponse>;
    byIndustrySector?: Array<IndustrySectorValueResponse>;
    byCountry?: Array<CountryValueResponse>;
    byAssetType?: Array<AssetTypeValueResponse>;
}

