/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Portfolio summary with total value and returns
 */
export interface PortfolioSummaryResponse { 
    totalValue?: number;
    totalInvested?: number;
    totalReturn?: number;
    totalReturnPercentage?: number;
    todayChange?: number;
    todayChangePercentage?: number;
}

