/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Portfolio concentration metrics and HHI
 */
export interface PortfolioConcentrationResponse { 
    top1?: number;
    top3?: number;
    top5?: number;
    top10?: number;
    hhi?: number;
}

