/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortfolioChartResponse { 
    dates?: Array<string>;
    invested?: Array<number>;
    marketValue?: Array<number>;
    plPercentage?: Array<number>;
}

