/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonthlyInvestedResponse } from './monthly-invested-response';
import { PortfolioChartResponse } from './portfolio-chart-response';


export interface PortfolioPerformanceResponse { 
    chart?: PortfolioChartResponse;
    monthlyInvested?: MonthlyInvestedResponse;
}

