/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodChangeResponse } from './period-change-response';


/**
 * Portfolio summary with total value and returns
 */
export interface PortfolioSummaryResponse { 
    snapshotDate?: string;
    totalValue?: number;
    totalInvested?: number;
    totalReturn?: number;
    totalReturnPercentage?: number;
    totalUnrealizedPL?: number;
    totalRealizedPL?: number;
    totalHoldings?: number;
    totalDividends?: number;
    periodChange?: PeriodChangeResponse;
}

