/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IndustrySimpleResponse } from './industry-simple-response';


export interface SectorResponse { 
    id?: string;
    name?: string;
    industries?: Array<IndustrySimpleResponse>;
}

