/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetResponse } from './asset-response';


export interface StagingTransactionResponse { 
    id?: string;
    platform?: StagingTransactionResponse.PlatformEnum;
    date?: string;
    type?: StagingTransactionResponse.TypeEnum;
    symbol?: string;
    quantity?: number;
    price?: number;
    amount?: number;
    resolvedAsset?: AssetResponse;
    importStatus?: StagingTransactionResponse.ImportStatusEnum;
}
export namespace StagingTransactionResponse {
    export const PlatformEnum = {
        Trading212: 'TRADING212',
        Etoro: 'ETORO',
        Ibkr: 'IBKR',
        Revolut: 'REVOLUT'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
    export const TypeEnum = {
        Buy: 'BUY',
        Fee: 'FEE',
        Sell: 'SELL',
        Deposit: 'DEPOSIT',
        Withdrawal: 'WITHDRAWAL',
        Dividend: 'DIVIDEND',
        DividendAdjustment: 'DIVIDEND_ADJUSTMENT',
        Unknown: 'UNKNOWN'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ImportStatusEnum = {
        Pending: 'PENDING',
        Validated: 'VALIDATED',
        Failed: 'FAILED',
        Imported: 'IMPORTED'
    } as const;
    export type ImportStatusEnum = typeof ImportStatusEnum[keyof typeof ImportStatusEnum];
}


