/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StagingTransactionEditRequest { 
    id: string;
    quantity?: number;
    price?: number;
    asset: string;
    amount?: number;
    grossAmount?: number;
    taxPercentage?: number;
    taxAmount?: number;
}

