/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformerResponse } from './performer-response';


export interface TopBottomPerformersResponse { 
    top?: Array<PerformerResponse>;
    bottom?: Array<PerformerResponse>;
}

