/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TotalDividendCostYieldResponse { 
    totalDividendEur?: number;
    annualizedDividendEur?: number;
    totalCostBasisEur?: number;
    daysHeld?: number;
    dividendCostYield?: number;
}

