/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetResponse } from './asset-response';
import { CurrencyResponse } from './currency-response';


export interface TransactionResponse { 
    id?: string;
    transactionType?: TransactionResponse.TransactionTypeEnum;
    platform?: TransactionResponse.PlatformEnum;
    date?: string;
    currency?: CurrencyResponse;
    asset?: AssetResponse;
    quantity?: number;
    price?: number;
    amount?: number;
    relatedTransactionId?: string;
    grossAmount?: number;
    taxAmount?: number;
    taxPercentage?: number;
}
export namespace TransactionResponse {
    export const TransactionTypeEnum = {
        Buy: 'BUY',
        Fee: 'FEE',
        Sell: 'SELL',
        Deposit: 'DEPOSIT',
        Withdrawal: 'WITHDRAWAL',
        Dividend: 'DIVIDEND',
        DividendAdjustment: 'DIVIDEND_ADJUSTMENT',
        Unknown: 'UNKNOWN'
    } as const;
    export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];
    export const PlatformEnum = {
        Trading212: 'TRADING212',
        Etoro: 'ETORO',
        Ibkr: 'IBKR',
        Revolut: 'REVOLUT'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


